# Generated by Django 5.1.4 on 2025-01-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_user_bio_user_name_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
